(()=>{
const key=()=>`lifeos_alignment_${localStorage.getItem('lifeos_current_profile')||'default'}`;
const load=()=>{try{return JSON.parse(localStorage.getItem(key()))||{checkins:[],memories:[],permissions:{sleep:true,nutrition:true,exercise:true,alcohol:true,goals:true,journal:true,relationships:true,wearables:false}}}catch{return{checkins:[],memories:[],permissions:{}}}};
const save=s=>localStorage.setItem(key(),JSON.stringify(s));
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function infer(text){const t=text.toLowerCase(), facts=[];let m;
 if((m=t.match(/(?:woke|got up|up) (?:at )?(\d{1,2})(?::(\d{2}))?/)))facts.push(['Wake',`${m[1]}:${m[2]||'00'}`]);
 if(/meditat|pray|visuali[sz]|stillness/.test(t))facts.push(['Stillness','mentioned']);
 if(/walk|gym|train|swam|swim|run|exercise/.test(t))facts.push(['Movement','mentioned']);
 if(/beer|wine|alcohol|drink/.test(t))facts.push(['Alcohol','mentioned']);
 if(/breakfast|lunch|dinner|meal|ate|food/.test(t))facts.push(['Nutrition','mentioned']);
 if((m=t.match(/energy(?: was| is|'s)?\s*(\d{1,2})/)))facts.push(['Energy',`${Math.min(10,+m[1])}/10`]);
 if(/tired|exhaust|sluggish|bloated/.test(t))facts.push(['Energy','low symptom mentioned']);
 if(/great|good|energised|energized|sharp|focused/.test(t))facts.push(['Positive','felt good/focused']);
 return facts;
}
function response(type,text,facts){const t=text.toLowerCase();if(type==='morning')return /woke|got up/.test(t)?'Good. Today is about direction, not perfection. Choose the one outcome that matters most and protect the conditions that make it easier.':'Tell me what matters most today and one thing your future self will thank you for tonight.';
 if(type==='midday'){if(/tired|sluggish|bloated/.test(t))return 'You sound lower on energy. Notice what preceded it—sleep, food, hydration, stress or workload—without jumping to conclusions. A short walk and water may be a useful reset.';return 'Quick alignment check: are you still spending your best attention on what you said mattered today?';}
 if(/didn.?t|missed|failed|late|bad/.test(t))return 'Not everything went to plan, but that is information rather than failure. Pick one small upstream change for tomorrow and continue.';
 return 'Capture complete. Keep what worked, notice what did not, and make tomorrow slightly easier rather than trying to make it perfect.';}
function alignment(text){const t=text.toLowerCase();return {Health:/walk|gym|train|exercise|healthy|sleep|water/.test(t)?'↑':'—',Energy:/energ|sharp|good/.test(t)?'↑':/tired|sluggish|exhaust/.test(t)?'↓':'—',Work:/finish|progress|focus|work|proposal|project/.test(t)?'✓':'—',People:/family|wife|husband|partner|child|kids|friend|mum|mom|dad/.test(t)?'✓':'—',Spirit:/meditat|pray|gratitude|visuali[sz]|stillness/.test(t)?'✓':'—'};}
function render(){if(document.getElementById('alignmentCoach'))return;const today=document.getElementById('today');if(!today)return;const host=document.createElement('section');host.id='alignmentCoach';host.className='coach-shell';host.innerHTML=`<article class="coach-hero"><small>YOUR AI LIFE COACH</small><h2>Live in alignment.</h2><p>Talk naturally. Life OS turns your check-ins into useful structure, patterns and gentle next actions.</p><div class="coach-actions"><button class="coach-action" data-coach="morning"><span>☀️</span>Set my day</button><button class="coach-action" data-coach="midday"><span>◐</span>Quick check-in</button><button class="coach-action" data-coach="evening"><span>🌙</span>Tell me about my day</button></div></article><article class="card coach-card coach-hidden" id="coachCapture"><h3 id="coachTitle">Check-in</h3><p class="next-muted">Speak for 30–90 seconds or type naturally.</p><textarea class="coach-transcript" id="coachText" data-voice-label="Life OS check in" placeholder="Tell Life OS what's going on…"></textarea><div class="coach-row"><button class="primary-button" id="coachSave">Save & reflect</button><button class="text-button" id="coachCancel">Cancel</button></div></article><article class="card coach-card" id="coachLatest"><h3>Coach</h3><div id="coachInsight" class="coach-insight">Your coach will use what you choose to share to help you stay aligned with the life you described.</div><div id="coachAlignment"></div></article><details class="card coach-card"><summary><strong>What Life OS knows about me</strong></summary><p class="coach-disclaimer">This prototype stores coaching data separately in your current browser profile. You control it. Future cloud AI and wearable analysis should be explicit opt-in.</p><div id="coachMemories" class="coach-memory"></div><button class="text-button" id="coachClear" type="button">Clear coaching memory</button></details>`;today.insertBefore(host,today.firstChild.nextSibling);bind();paint();}
let mode='morning';function bind(){document.querySelectorAll('[data-coach]').forEach(b=>b.onclick=()=>{mode=b.dataset.coach;document.getElementById('coachTitle').textContent=mode==='morning'?'Set my day':mode==='midday'?'Quick check-in':'Tell me about my day';document.getElementById('coachCapture').classList.remove('coach-hidden');document.getElementById('coachText').focus()});document.getElementById('coachCancel').onclick=()=>document.getElementById('coachCapture').classList.add('coach-hidden');document.getElementById('coachSave').onclick=()=>{const text=document.getElementById('coachText').value.trim();if(!text)return;const s=load(),facts=infer(text),item={id:Date.now(),at:new Date().toISOString(),type:mode,text,facts,alignment:alignment(text),response:response(mode,text,facts)};s.checkins.unshift(item);facts.forEach(f=>s.memories.unshift({id:`${item.id}-${f[0]}`,at:item.at,label:f[0],value:f[1]}));s.memories=s.memories.slice(0,40);save(s);document.getElementById('coachText').value='';document.getElementById('coachCapture').classList.add('coach-hidden');paint()};document.getElementById('coachClear').onclick=()=>{if(confirm('Clear Life OS coaching check-ins and learned observations on this device?')){save({checkins:[],memories:[],permissions:{}});paint()}};}
function paint(){const s=load(),x=s.checkins[0];document.getElementById('coachInsight').textContent=x?x.response:'Your coach will use what you choose to share to help you stay aligned with the life you described.';const a=document.getElementById('coachAlignment');a.innerHTML=x?`<div class="coach-alignment">${Object.entries(x.alignment).map(([k,v])=>`<div class="coach-align-item"><strong>${v}</strong><small>${k}</small></div>`).join('')}</div><p class="coach-disclaimer">Alignment reflects only what you mentioned. It is not a medical assessment or a judgement of you.</p>`:'';document.getElementById('coachMemories').innerHTML=s.memories.length?s.memories.slice(0,12).map(m=>`<div class="coach-memory-item"><span><strong>${esc(m.label)}</strong> · ${esc(m.value)}</span><small>${new Date(m.at).toLocaleDateString()}</small></div>`).join(''):'<p class="coach-disclaimer">No learned observations yet.</p>';}
const obs=new MutationObserver(()=>{if(!document.getElementById('alignmentCoach'))render()});document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>{render();obs.observe(document.body,{childList:true,subtree:true})}):render();
})();