(() => {
  const config=window.LIFE_OS_CLOUD||{};
  const configured=Boolean(config.url&&config.publishableKey&&window.supabase?.createClient);
  const client=configured?window.supabase.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
  let session=null,syncTimer=null,listeners=[];
  const emit=detail=>listeners.forEach(listener=>listener(detail));
  async function current(){if(!client)return {configured:false,session:null};const {data}=await client.auth.getSession();session=data.session;return {configured:true,session}}
  async function signIn(email){if(!client)throw new Error('Cloud sync has not been connected yet.');const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}});if(error)throw error;return true}
  async function signOut(){if(!client)return;const {error}=await client.auth.signOut();if(error)throw error;session=null;emit({type:'signed-out'})}
  async function deleteAccount(){if(!client||!session)throw new Error('Sign in first.');const {error}=await client.rpc('delete_my_account');if(error)throw error;await client.auth.signOut({scope:'local'});session=null;emit({type:'signed-out'})}
  async function save(profile,state){if(!client||!session)return false;const userId=session.user.id;const profileRow={id:userId,first_name:profile.name,family_name:profile.familyName||'',way_name:profile.wayName||'',life_mode:profile.lifeMode||'personal',purpose:profile.purpose,principles:profile.principles,routine_config:profile.routineConfig||{},trackers:profile.trackers||{},updated_at:new Date().toISOString()};const [{error:profileError},{error:dataError}]=await Promise.all([client.from('profiles').upsert(profileRow),client.from('life_data').upsert({user_id:userId,state,updated_at:new Date().toISOString()})]);if(profileError||dataError)throw profileError||dataError;emit({type:'synced',at:new Date().toISOString()});return true}
  function queueSave(profile,state){if(!client||!session)return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>save(profile,state).catch(error=>emit({type:'error',message:error.message})),700)}
  async function load(){if(!client||!session)return null;const userId=session.user.id;const [{data:profile,error:profileError},{data:life,error:lifeError}]=await Promise.all([client.from('profiles').select('*').eq('id',userId).maybeSingle(),client.from('life_data').select('state').eq('user_id',userId).maybeSingle()]);if(profileError||lifeError)throw profileError||lifeError;if(!profile&&!life)return null;return {profile:profile?{id:`cloud-${userId}`,name:profile.first_name,familyName:profile.family_name,wayName:profile.way_name||'',lifeMode:profile.life_mode||'personal',purpose:profile.purpose,principles:profile.principles,routineConfig:profile.routine_config||{},trackers:profile.trackers||{},cloudUserId:userId}:null,state:life?.state||null}}
  async function family(){if(!client||!session)return null;const {data:membership,error:membershipError}=await client.from('family_members').select('family_id,role').eq('user_id',session.user.id).limit(1).maybeSingle();if(membershipError)throw membershipError;if(!membership)return null;const [{data:space,error:spaceError},{data:invite,error:inviteError}]=await Promise.all([client.from('family_spaces').select('id,name,principles').eq('id',membership.family_id).single(),client.from('family_invites').select('code,expires_at').eq('family_id',membership.family_id).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(1).maybeSingle()]);if(spaceError)throw spaceError;if(inviteError&&membership.role!=='member')throw inviteError;return {...space,role:membership.role,inviteCode:invite?.code||''}}
  async function createFamily(name,principles){if(!client||!session)throw new Error('Sign in first.');const {data,error}=await client.rpc('create_family_space',{space_name:name,space_principles:principles});if(error)throw error;return data}
  async function joinFamily(code){if(!client||!session)throw new Error('Sign in first.');const {data,error}=await client.rpc('join_family_space',{invite_code:code});if(error)throw error;return data}
  async function saveFamilyPrinciples(familyId,principles){if(!client||!session)throw new Error('Sign in first.');const {error}=await client.from('family_spaces').update({principles}).eq('id',familyId);if(error)throw error;emit({type:'family-synced'});return true}
  if(client)client.auth.onAuthStateChange((event,newSession)=>{session=newSession;emit({type:event.toLowerCase(),session:newSession})});
  window.LifeOSCloud={configured,client,current,signIn,signOut,deleteAccount,save,queueSave,load,family,createFamily,joinFamily,saveFamilyPrinciples,on(listener){listeners.push(listener);return()=>{listeners=listeners.filter(item=>item!==listener)}}};
})();
