(()=>{
const stageFor=()=>{const h=new Date().getHours();if(h<9)return'morning';if(h<12)return'focus';if(h<15)return'reset';return'evening'};
const stages={morning:{title:'Start well',copy:'Keep the first hour simple. Wake your body, centre your mind, then choose what matters.',steps:['Drink water','Light, wash and get ready','5 minutes of meditation / visualisation','Read your identity / principles','Choose today\'s #1 outcome'],target:'#morningChecks'},focus:{title:'Protect your best attention',copy:'One important thing before the day fills up.',steps:['Review your #1 priority','Phone away','Work deeply on the important outcome','Pause before switching tasks'],target:'#priorityList'},reset:{title:'Reset your energy',copy:'Check your direction, fuel and energy without overcomplicating it.',steps:['Tell Life OS how you feel','Eat deliberately','Take a 10-minute walk','Return to the next clear action'],target:'#alignmentCoach'},evening:{title:'Close the day properly',copy:'Finish well so tomorrow starts easier.',steps:['Finish or park open loops','Be present with people who matter','Prepare tomorrow','8:30 read / wind down','Protect bedtime'],target:'#dailyWin'}};
function create(){const today=document.getElementById('today');if(!today||document.getElementById('dailyGuide'))return;const host=document.createElement('section');host.id='dailyGuide';host.className='daily-guide';document.querySelector('#today .hero')?.insertAdjacentElement('afterend',host);simplifyToday();render(stageFor());simplifyNav()}
function render(name){const s=stages[name],host=document.getElementById('dailyGuide');if(!host)return;host.innerHTML=`<article class="daily-now"><p class="eyebrow">WHAT TO DO NOW</p><h2>${s.title}</h2><p>${s.copy}</p><div class="daily-steps">${s.steps.map((x,i)=>`<div class="daily-step"><strong>${i+1}</strong><span>${x}</span></div>`).join('')}</div><button class="primary-button daily-cta" id="dailyContinue">Start this step →</button><div class="daily-stage-nav">${Object.keys(stages).map(k=>`<button data-stage="${k}" class="${k===name?'active':''}">${k[0].toUpperCase()+k.slice(1)}</button>`).join('')}</div></article><div class="daily-next"><div><small>Life OS principle</small><strong>What should I do now?</strong></div><span>Keep it simple.</span></div>`;host.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>render(b.dataset.stage));document.getElementById('dailyContinue').onclick=()=>reveal(s.target,name)}
function simplifyToday(){const today=document.getElementById('today');if(!today)return;[...today.children].forEach(el=>{if(el.id==='dailyGuide'||el.classList.contains('hero')||el.classList.contains('saved-note'))return;el.classList.add('daily-secondary')})}
function reveal(selector,name){document.querySelectorAll('#today>.daily-secondary').forEach(el=>el.classList.remove('daily-revealed'));const target=document.querySelector(selector);if(!target)return;const block=target.id==='alignmentCoach'?target:target.closest('#today>section,#today>article')||target.parentElement;block.classList.add('daily-revealed');if(!block.querySelector('.daily-back')){const b=document.createElement('button');b.className='daily-back';b.type='button';b.textContent='← Back to my guide';b.onclick=()=>{block.classList.remove('daily-revealed');document.getElementById('dailyGuide')?.scrollIntoView({behavior:'smooth',block:'start'})};block.prepend(b)}setTimeout(()=>target.scrollIntoView({behavior:'smooth',block:'center'}),30);if(name==='reset')setTimeout(()=>document.querySelector('[data-coach="checkin"]')?.click(),150)}
function activate(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.bottom-nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===id));window.scrollTo({top:0,behavior:'smooth'})}
function simplifyNav(){const nav=document.querySelector('.bottom-nav');if(!nav)return;nav.classList.add('daily-simple');nav.innerHTML=`<a href="#today" data-route="today" class="active"><span>⌂</span><small>Today</small></a><a href="#goals" data-route="goals"><span>◎</span><small>Progress</small></a><a href="#today" id="coachNav"><span>◐</span><small>Coach</small></a><a href="#wholelife" data-route="wholelife"><span>○</span><small>Life</small></a>`;nav.querySelectorAll('a[data-route]').forEach(a=>a.onclick=e=>{e.preventDefault();const id=a.dataset.route;if(!document.getElementById(id))return;history.replaceState(null,'',`#${id}`);activate(id)});document.getElementById('coachNav').onclick=e=>{e.preventDefault();history.replaceState(null,'','#today');activate('today');reveal('#alignmentCoach','reset')}}
function refresh(){if(!document.getElementById('dailyGuide'))create();else render(stageFor())}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',()=>setTimeout(create,160));else setTimeout(create,160);setInterval(refresh,15*60*1000);
})();