(()=>{
const REG='life-os-profiles-v1',date=()=>new Date().toISOString().slice(0,10);let pid='guest',state={};
const profile=()=>{try{const r=JSON.parse(localStorage.getItem(REG));return r?.items?.find(x=>x.id===r.activeId)||null}catch{return null}};
const key=()=>`life-os-whole:${pid}`;const save=()=>localStorage.setItem(key(),JSON.stringify(state));
const load=()=>{const p=profile();pid=p?.id||'guest';state={daily:{},openLoops:[],people:[],life:[],monthly:{},wearables:{apple:false,fitbit:false,healthConnect:false},...(JSON.parse(localStorage.getItem(key())||'{}'))};return p};
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const day=()=>state.daily[date()]||(state.daily[date()]={scores:{health:7,energy:7,mind:7,spirit:7,relationships:7,family:7,work:7,money:7,growth:7,joy:7},checks:{}});
const pillars=[['spirit','Spirit & stillness','A little silence before more noise.',['gratitude','stillness','nature','kindness']],['sleep','Sleep','Protect tomorrow tonight.',['sleepRoutine','sleepEnough','morningLight']],['nutrition','Nutrition','Fuel energy, not perfection.',['protein','vegetables','fruit','water','wholeFoods']],['movement','Movement','Strength, cardio, walking, mobility and recovery.',['strength','cardio','walk','mobility']],['relationships','Relationships','Give important people deliberate attention.',['partner','familyTime','friend']],['digital','Digital health','Use technology; do not surrender attention to it.',['noPhoneMorning','noPhoneBed','deepWorkPhoneAway']],['environment','Environment','Reduce friction by resetting the space around you.',['desk','bedroom','kitchen','tomorrowReady']],['recovery','Recovery','Recovery is part of performance.',['recovery','outside','hobby']],['prevent','Preventative health','Keep the boring, important health maintenance visible.',['dental','eyes','healthAdmin']],['joy','Joy & adventure','Build a life worth being productive for.',['joy','lookForward']]];
const labels={gratitude:'Gratitude',stillness:'Prayer / meditation / silence',nature:'Nature / outside',kindness:'Kindness / service',sleepRoutine:'Protected bedtime routine',sleepEnough:'Enough sleep',morningLight:'Morning light',protein:'Protein',vegetables:'Vegetables',fruit:'Fruit',water:'Water',wholeFoods:'Mostly whole foods',strength:'Strength',cardio:'Cardio',walk:'Walking',mobility:'Mobility',partner:'Partner / close relationship',familyTime:'Family presence',friend:'Friend / meaningful connection',noPhoneMorning:'No phone first 30 min',noPhoneBed:'No phone in bed',deepWorkPhoneAway:'Phone away in deep work',desk:'Desk clear',bedroom:'Bedroom ready',kitchen:'Kitchen reset',tomorrowReady:'Tomorrow prepared',recovery:'Deliberate recovery',outside:'Fresh air / outside',hobby:'Read / hobby / switch off',dental:'Dental up to date',eyes:'Eyes / vision up to date',healthAdmin:'Health admin current',joy:'Did something enjoyable',lookForward:'Something to look forward to'};
function mount(){load();if(!document.getElementById('wholelife')){const s=document.createElement('section');s.className='view';s.id='wholelife';s.dataset.title='Whole Life';document.querySelector('main').appendChild(s);const nav=document.querySelector('.bottom-nav');if(nav){const a=document.createElement('a');a.href='#wholelife';a.innerHTML='<span>◉</span><small>Life</small>';nav.appendChild(a)}}render();window.addEventListener('hashchange',()=>{if(location.hash==='#wholelife'){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='wholelife'));document.querySelectorAll('.bottom-nav a').forEach(a=>a.classList.toggle('active',a.hash==='#wholelife'));render()}});if(location.hash==='#wholelife')location.dispatchEvent(new HashChangeEvent('hashchange'))}
function render(){load();const d=day(),checked=Object.values(d.checks).filter(Boolean).length,total=Object.keys(labels).length,avg=Math.round(Object.values(d.scores).reduce((a,b)=>a+Number(b||0),0)/10*10)/10;document.getElementById('wholelife').innerHTML=`<div class="page-intro"><p class="eyebrow">BUILD THE WHOLE LIFE</p><h1>Healthy. Clear. Connected. Alive.</h1><p>Build a successful life without sacrificing the things that make success worth having.</p></div><div class="whole-summary"><div class="whole-stat"><strong>${avg}</strong><span>Life balance</span></div><div class="whole-stat"><strong>${checked}</strong><span>Signals today</span></div><div class="whole-stat"><strong>${state.openLoops.filter(x=>!x.done).length}</strong><span>Open loops</span></div></div><article class="card"><p class="eyebrow">DAILY LIFE OS</p><h2 style="font-family:Georgia,serif">Small signals, not another job</h2><div class="whole-pillars">${pillars.map(pillar).join('')}</div></article>${radar(d)}${capture()}${people()}${life()}${money()}${wearables()}`;bind()}
function pillar([id,title,desc,checks]){const d=day();return `<article class="card whole-pillar"><h3>${title}</h3><p>${desc}</p><div class="whole-mini-checks">${checks.map(k=>`<label class="whole-mini-check"><input type="checkbox" data-whole-check="${k}" ${d.checks[k]?'checked':''}>${labels[k]}</label>`).join('')}</div></article>`}
function radar(d){const items=[['health','Health'],['energy','Energy'],['mind','Mind'],['spirit','Spirit'],['relationships','Relationships'],['family','Family'],['work','Work'],['money','Money'],['growth','Growth'],['joy','Fun / joy']];return `<details class="card whole-section"><summary>Weekly Life Balance Radar</summary><p class="next-muted">Do not maximise every score. Notice what is being neglected.</p><div class="whole-radar">${items.map(([k,l])=>`<label>${l}<input type="number" min="1" max="10" value="${d.scores[k]||7}" data-whole-score="${k}"></label>`).join('')}</div></details>`}
function capture(){return `<details class="card whole-section" open><summary>Get It Out Of My Head</summary><p class="next-muted">Capture the open loop. Decide what it is later.</p><form id="wholeCapture" class="whole-capture"><input id="wholeCaptureText" required data-voice-label="open loop" placeholder="Book dentist, call John, renew insurance…"><button class="secondary-button">Capture</button></form><div class="whole-list">${state.openLoops.filter(x=>!x.done).slice(-8).reverse().map(x=>`<div class="whole-list-item"><span>${esc(x.text)}</span><button class="text-button" data-loopdone="${x.id}">Done</button></div>`).join('')}</div></details>`}
function people(){return `<details class="card whole-section"><summary>People Who Matter</summary><p class="next-muted">Relationships deserve more than whatever time is left over.</p><form id="peopleForm" class="whole-capture"><input id="personText" required data-voice-label="person who matters" placeholder="Name — connection I want to protect"><button class="secondary-button">Add</button></form><div class="whole-list">${state.people.map(x=>`<div class="whole-list-item"><span>${esc(x.text)}</span><small>${esc(x.last||'Keep connected')}</small></div>`).join('')}</div></details>`}
function life(){return `<details class="card whole-section"><summary>Life, Joy & Adventure</summary><p class="next-muted">Things to do, see, learn, experience and share.</p><form id="lifeForm" class="whole-capture"><input id="lifeText" required data-voice-label="life experience" placeholder="Something I want to experience or look forward to…"><button class="secondary-button">Add</button></form><div class="whole-list">${state.life.slice(-8).reverse().map(x=>`<div class="whole-list-item"><span>${esc(x.text)}</span><small>${esc(x.type||'Life')}</small></div>`).join('')}</div></details>`}
function money(){const m=state.monthly;return `<details class="card whole-section"><summary>Monthly Financial Health</summary><p class="next-muted">Direction, not expense obsession.</p><div class="next-grid"><div class="next-field"><label>Financial priority</label><input data-monthly="priority" value="${esc(m.priority||'')}" placeholder="Emergency fund, debt, investing, runway…"></div><div class="next-field"><label>Is my financial life moving in the right direction?</label><textarea data-monthly="direction">${esc(m.direction||'')}</textarea></div><div class="next-field"><label>Highest-return use of capital now</label><textarea data-monthly="capital">${esc(m.capital||'')}</textarea></div></div></details>`}
function wearables(){return `<details class="card whole-section"><summary>Wearables & Health Data</summary><p class="next-muted">Integration-ready. Manual Life OS data remains useful now; approved wearable data can replace duplicate entry later.</p><div class="wearable-grid"><div class="wearable-card"><strong>Apple Health / Apple Watch</strong><span>Sleep, activity, heart-rate and workout signals</span><i class="wearable-status">Planned</i></div><div class="wearable-card"><strong>Fitbit</strong><span>Sleep, steps, activity and recovery signals</span><i class="wearable-status">Planned</i></div><div class="wearable-card"><strong>Health Connect</strong><span>Android health-data interoperability</span><i class="wearable-status">Planned</i></div></div><div class="whole-note">Design rule: wearable connections must be opt-in, explain exactly what data is read, minimise stored health data, and never silently convert health signals into medical diagnoses.</div></details>`}
function bind(){document.querySelectorAll('[data-whole-check]').forEach(e=>e.onchange=()=>{day().checks[e.dataset.wholeCheck]=e.checked;save()});document.querySelectorAll('[data-whole-score]').forEach(e=>e.onchange=()=>{day().scores[e.dataset.wholeScore]=Number(e.value);save()});document.querySelectorAll('[data-monthly]').forEach(e=>e.onchange=()=>{state.monthly[e.dataset.monthly]=e.value;save()});const c=document.getElementById('wholeCapture');if(c)c.onsubmit=e=>{e.preventDefault();state.openLoops.push({id:Date.now(),text:wholeCaptureText.value.trim(),done:false});save();render()};document.querySelectorAll('[data-loopdone]').forEach(b=>b.onclick=()=>{const x=state.openLoops.find(v=>String(v.id)===b.dataset.loopdone);if(x)x.done=true;save();render()});const p=document.getElementById('peopleForm');if(p)p.onsubmit=e=>{e.preventDefault();state.people.push({id:Date.now(),text:personText.value.trim()});save();render()};const l=document.getElementById('lifeForm');if(l)l.onsubmit=e=>{e.preventDefault();state.life.push({id:Date.now(),text:lifeText.value.trim(),type:'Life'});save();render()}}
window.addEventListener('DOMContentLoaded',mount);
})();